export enum ApplicationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  OFFERED = "OFFERED",
  REJECTED = "REJECTED",
}

export enum UserRole {
  APPLICANT = "APPLICANT",
  STUDENT = "STUDENT",
  STAFF = "STAFF",
  ADMIN = "ADMIN",
  FINANCE = "FINANCE",
}
